### ISSUE TITLE
AX3000-5.15分支，在4月16日更新后，AX6S编译失败

### ISSUE THREAD

**Issue by chika0801** [1715173329/imoutowrt#564]
我在4月14日编译过是成功的，16日更新了，再编译就一直失败，看日志是和MT76WIFI驱动有关，不知道怎么处理。
<pre>
make  -C "/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.10.110" KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Apr 15 22:59:22 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/workdir/openwrt/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/symvers/cryptodev-linux.symvers /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/symvers/gpio-button-hotplug.symvers /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/symvers/mac80211.symvers" KERNELRELEASE=5.10.110 CONFIG_MT76_CONNAC_LIB=m CONFIG_MT7615_COMMON=m CONFIG_MT7615E=m CONFIG_MT7622_WMAC=y CONFIG_MT7915E=m M="/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060" NOSTDINC_FLAGS="-nostdinc  -isystem /workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.2.0_musl/lib/gcc/aarch64-openwrt-linux-musl/11.2.0/include -I/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060 -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/uapi -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211/uapi -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211 -include backport/autoconf.h -include backport/backport.h -DCONFIG_MAC80211_MESH -DCONFIG_MT7622_WMAC" modules
make[4]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.10.110'
  CC [M]  /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.o
/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.c: In function 'mt7915_init_wiphy':
/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.c:330:44: error: 'IEEE80211_MAX_AMPDU_BUF' undeclared (first use in this function); did you mean 'IEEE80211_MIN_AMPDU_BUF'?
  330 |         hw->max_rx_aggregation_subframes = IEEE80211_MAX_AMPDU_BUF;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
      |                                            IEEE80211_MIN_AMPDU_BUF
/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.c:330:44: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [scripts/Makefile.build:280: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.o] Error 1
make[5]: *** [scripts/Makefile.build:497: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915] Error 2
make[4]: *** [Makefile:1822: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060] Error 2
make[3]: *** [Makefile:469: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/.built] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.10.110'
make[3]: Leaving directory '/workdir/openwrt/package/kernel/mt76'
time: package/kernel/mt76/compile#1.25#0.27#1.51
    ERROR: package/kernel/mt76 failed to build.
make[2]: *** [package/Makefile:116: package/kernel/mt76/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.
</pre>

**Comment by chika0801** [comment]
<pre>
-- Build files have been written to: /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/tools
touch /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/.configured_b1c6ae92f8e974e60b47b3e5ad3573cc
rm -f /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/.built
touch /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/.built_check
make  -C "/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.10.110" KCFLAGS="-fmacro-prefix-map=/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl" HOSTCFLAGS="-O2 -I/home/chika/openwrt/staging_dir/host/include -I/home/chika/openwrt/staging_dir/hostpkg/include -I/home/chika/openwrt/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Apr 15 22:59:22 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/chika/openwrt/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/chika/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/symvers/cryptodev-linux.symvers /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/symvers/gpio-button-hotplug.symvers /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/symvers/mac80211.symvers" KERNELRELEASE=5.10.110 CONFIG_MT76_CONNAC_LIB=m CONFIG_MT7615_COMMON=m CONFIG_MT7615E=m CONFIG_MT7622_WMAC=y CONFIG_MT7915E=m M="/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060" NOSTDINC_FLAGS="-nostdinc  -isystem /home/chika/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.2.0_musl/lib/gcc/aarch64-openwrt-linux-musl/11.2.0/include -I/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060 -I/home/chika/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/uapi -I/home/chika/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport -I/home/chika/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211/uapi -I/home/chika/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211 -include backport/autoconf.h -include backport/backport.h -DCONFIG_MAC80211_MESH -DCONFIG_MT7622_WMAC" modules
make[4]: Entering directory '/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.10.110'
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/main.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/init.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/mcu.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/eeprom.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/mac.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/debugfs.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/trace.o
  LD [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/mt7615-common.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/pci.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/pci_init.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/dma.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/pci_mac.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/mmio.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/soc.o
  LD [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7615/mt7615e.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/pci.o
  CC [M]  /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.o
/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.c: In function 'mt7915_init_wiphy':
/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.c:330:44: error: 'IEEE80211_MAX_AMPDU_BUF' undeclared (first use in this function); did you mean 'IEEE80211_MIN_AMPDU_BUF'?
  330 |         hw->max_rx_aggregation_subframes = IEEE80211_MAX_AMPDU_BUF;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
      |                                            IEEE80211_MIN_AMPDU_BUF
/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.c:330:44: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [scripts/Makefile.build:280: /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915/init.o] Error 1
make[5]: *** [scripts/Makefile.build:497: /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/mt7915] Error 2
make[4]: *** [Makefile:1822: /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060] Error 2
make[4]: Leaving directory '/home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.10.110'
make[3]: *** [Makefile:469: /home/chika/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-04-07-506bb060/.built] Error 2
make[3]: Leaving directory '/home/chika/openwrt/package/kernel/mt76'
time: package/kernel/mt76/compile#10.03#1.00#11.02
    ERROR: package/kernel/mt76 failed to build.
make[2]: *** [package/Makefile:116: package/kernel/mt76/compile] Error 1
make[2]: Leaving directory '/home/chika/openwrt'
make[1]: *** [package/Makefile:110: /home/chika/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/chika/openwrt'
make: *** [/home/chika/openwrt/include/toplevel.mk:230: world] Error 2
chika@AMD-01:~/openwrt$ 

</pre>

试几回了也是一样的错误提示

**Comment by 1715173329** [comment]
这是给 ipq807x 用的，不要编译 ax6s
如有需求请移步至主线 immortalwrt 项目。
建议使用 openwrt-18.06-k5.4 分支。

**Comment by chika0801** [comment]
> 这是给 ipq807x 用的，不要编译 ax6s 如有需求请移步至主线 immortalwrt 项目。 建议使用 openwrt-18.06-k5.4 分支。

谢谢您的回复，祝你身体健康。
